### ISSUE TITLE
URL dans les slides erronées

### ISSUE THREAD

**Issue by gmembre-zenika** [l0rd/containerspatterns#1]
Les urls dans les slides vers ton github sont erronées : 
exemple : https://l0rd.github.io/containerspatterns/#22
le lien est https://github/l0rd/containerspatterns/DSM alors qu'il devrait être https://github.com/l0rd/containerspatterns/tree/master/DSM

idem pour les autres slides

**Comment by atrakic** [comment]
you need to fix your urlon your main.md , otherwise good job. thx
